action_match_rate_max: 1.0
action_match_rate_mean: 0.7489327405169517
action_match_rate_min: 0.3023255813953488
alpha: 1.0
batch_size: 256
completed_epochs: 1
early_stopped: false
epochs: 200
gamma: 0.99
learning_rate: 0.0001
n_episodes: 2556
n_features: 45
n_transitions: 85438
nan_count_total: 0
test_returns_mean: .nan
test_returns_std: .nan
